### ISSUE TITLE
[building]/usr/bin/ld: cannot find -lFALSE

### ISSUE THREAD

**Issue by YuehChuan** [AIS-Bonn/catch_ros#1]
when i catkin build got this error, env. ubuntu14.04.5 Indigo , thanks in advance.
seems no library FALSE when building depth filter_
______________________________________________________________________________
Errors     << depth_filler:make /home/schwarm/nimbo_picking/catkin_ws/logs/depth_filler/build.make.005.log
/usr/bin/ld: cannot find -lFALSE
collect2: error: ld returned 1 exit status
make[2]: *** [/home/schwarm/nimbo_picking/catkin_ws/devel/.private/depth_filler/lib/depth_filler/solve_test] Error 1
make[1]: *** [CMakeFiles/solve_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/schwarm/nimbo_picking/catkin_ws/src/nimbro_picking/depth_filler/src/depth_filler.cpp:41:2: warning: #warning Using very slow built-in Eigen BiCGSTAB solver. Install KLU! [-Wcpp]
 #warning Using very slow built-in Eigen BiCGSTAB solver. Install KLU!
  ^
/home/schwarm/nimbo_picking/catkin_ws/src/nimbro_picking/depth_filler/src/depth_filler.cpp: In member function ‘void depth_filler::DepthFillerPrivate::solve()’:
/home/schwarm/nimbo_picking/catkin_ws/src/nimbro_picking/depth_filler/src/depth_filler.cpp:366:51: error: no matching function for call to ‘Eigen::BiCGSTAB<Eigen::MappedSparseMatrix<float, 1> >::compute(Eigen::SparseMatrix<float>)’
   solver.compute(Eigen::SparseMatrix<SolveType>(A));
                                                   ^
/home/schwarm/nimbo_picking/catkin_ws/src/nimbro_picking/depth_filler/src/depth_filler.cpp:366:51: note: candidate is:
In file included from /usr/include/eigen3/Eigen/IterativeLinearSolvers:32:0,
                 from /usr/include/eigen3/Eigen/Sparse:24,
                 from /home/schwarm/nimbo_picking/catkin_ws/src/nimbro_picking/depth_filler/src/depth_filler.cpp:9:
/usr/include/eigen3/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h:103:12: note: Derived& Eigen::IterativeSolverBase<Derived>::compute(const MatrixType&) [with Derived = Eigen::BiCGSTAB<Eigen::MappedSparseMatrix<float, 1> >; Eigen::IterativeSolverBase<Derived>::MatrixType = Eigen::MappedSparseMatrix<float, 1>]
   Derived& compute(const MatrixType& A)
            ^
/usr/include/eigen3/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h:103:12: note:   no known conversion for argument 1 from ‘Eigen::SparseMatrix<float>’ to ‘const MatrixType& {aka const Eigen::MappedSparseMatrix<float, 1>&}’
make[2]: *** [CMakeFiles/depth_filler.dir/src/depth_filler.cpp.o] Error 1
make[1]: *** [CMakeFiles/depth_filler.dir/all] Error 2
make: *** [all] Error 2
cd /home/schwarm/nimbo_picking/catkin_ws/build/depth_filler; catkin build --get-env depth_filler | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << depth_filler:make                         [ Exited with code 2 ] 
Failed    <<< depth_filler                              [ 6.9 seconds ]        
Abandoned <<< nimbro_realsense                          [ Unrelated job failed ]
Abandoned <<< nimbro_keyframe_server                    [ Unrelated job failed ]
Abandoned <<< apc_capture                               [ Unrelated job failed ]
Abandoned <<< apc_6dpose                                [ Unrelated job failed ]
Abandoned <<< apc_densecap                              [ Unrelated job failed ]
Abandoned <<< apc_ros_player                            [ Unrelated job failed ]
Abandoned <<< apc_segmentation                          [ Unrelated job failed ]
Abandoned <<< apc_perception                            [ Unrelated job failed ]
Abandoned <<< apc_shelf_registration                    [ Unrelated job failed ]
Abandoned <<< apc_world                                 [ Unrelated job failed ]
Abandoned <<< nimbro_keyframe_editor                    [ Unrelated job failed ]
Abandoned <<< apc_control                               [ Unrelated job failed ]
Abandoned <<< apc_motion                                [ Unrelated job failed ]
catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS=-Wall[build - 20.2] [34/49 complete] [3/4 jobs] [0 queued] [1 failed] [apc_kinem.Finished  <<< nimbro_collision_detection                [ 15.3 seconds ]       
Finished  <<< apc_kinematics                            [ 29.1 seconds ]                                     
[build] Summary: 35 of 49 packages succeeded.                                                                
[build]   Ignored:   None.                                                                                   
[build]   Warnings:  None.                                                                                   
[build]   Abandoned: 13 packages were abandoned.                                                             
[build]   Failed:    1 packages failed.                                                                      
[build] Runtime: 40.4 seconds total.                                                                         
schwarm@schwarm:~/nimbo_picking/catkin_ws$ catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS=-Wall

![nimbo](https://user-images.githubusercontent.com/7314531/31023365-2a9292fe-a56e-11e7-9bb5-e3398ff879fe.png)

**Comment by xqms** [comment]
Hi, this is the wrong place to report this (here would be better: https://github.com/warehouse-picking-automation-challenges/nimbro_picking).

Nevertheless, please try to install `libsuitesparse-dev`, delete the build/depth_filler directory, and build again.

**Comment by YuehChuan** [comment]
@xqms thanks

**Comment by YuehChuan** [comment]
still get no luck

**Comment by xqms** [comment]
Did you delete the `build` directory in your workspace? You need to do that to trigger a full cmake run, so that it detects the newly installed package.

Nevertheless, I'm closing this since it is not an issue with catch_ros. Please open a new ticket on 
https://github.com/warehouse-picking-automation-challenges/nimbro_picking if the issue persists.

**Comment by YuehChuan** [comment]
oops, thank you.
