### ISSUE TITLE
[enhancment][report] tests equal to test cases not assertions

### ISSUE THREAD

**Issue by naveedhd** [AIS-Bonn/catch_ros#10]
the generated `xml` reports tests cases equal to assertions which I think should be equal to test cases.

example:
```
#include <catch_ros/catch.hpp>

TEST_CASE("test foo", "[Foo]")
{
  REQUIRE(true);
  REQUIRE(!false);
}
```

will result in test_result:
```
<testsuites errors="0" failures="0" tests="2"> 
...
```

**Comment by xqms** [comment]
Thanks for the report! I'm not too familiar with the jUnit XML format, but it seems you are right.

I don't have time to look into this right now, but I'd appreciate a PR ;-)
Otherwise I'll fix it when I come back to this.
