### ISSUE TITLE
Doctest as alternative

### ISSUE THREAD

**Issue by AlexReimann** [AIS-Bonn/catch_ros#17]
hi,
this is not really an issue, but rather a quick discussion question:

While searching for examples of your usage of `catch_ros` I found  that you switched to using doctest  for one of your repos:
https://github.com/AIS-Bonn/stillleben/commit/0a81d801fc746c505a2258865cecefde98b66ee5

Why did you switch and would you rather recommend using doctest instead of catch2?

I'm trying to settle for a testing framework for a larger project

**Comment by AlexReimann** [comment]
Okay, I found this: https://github.com/doctest/doctest/blob/master/doc/markdown/faq.md#how-is-doctest-different-from-catch

Still I'd like your view on the topic if you have time

**Comment by xqms** [comment]
Hey, I personally really like doctest, since it brings compilation times down by a large amount. Still, for ROS projects I tend to stick to `catch_ros`, since it has all the wrappers & CMake support that makes it easy to use together with `rostest`.
So maybe we need a `doctest_ros` package ;)

**Comment by AlexReimann** [comment]
Okay, thank you for the answer.
I'll probably stick to catch for the time being as migrating to doctest later seems also not to be too hard (if compile times become an issue)
