### ISSUE TITLE
proposed updates

### ISSUE THREAD

**Issue by mez** [AIS-Bonn/catch_ros#4]
Hello, 
I forked this and upgraded catch to 2.4.2 and added forkit 2.0.5 header to allow mocking. The commit is here: https://github.com/mez/catch_ros/commit/1458ea38124540f198ca1c4e661106440f55e238

Is it possible we add this change to your repo? I have that work done but I can't push to your repo. What do you think of these changes?

**Comment by xqms** [comment]
Thanks, that looks interesting! I wasn't aware of the FakeIt library, seems very useful.

In general, the method for "pushing" code to other repos on GitHub are pull requests. Could you open a separate pull request for updating the Catch version and for the inclusion of the FakeIt library?

I won't promise yet that I will take the FakeIt one, for several reasons:

 * The reason for catch_ros to exist are the provided cmake macros and C++ parts that make it easy to use Catch for testing ROS nodes. For FakeIt, nothing much extra is required - just dump the header in your own package, use catch_ros as before, and you are done.
 * FakeIt has another license (MIT vs. BSL)
 * Maybe it would be better to create a new ROS wrapper for FakeIt.

But we can discuss that in the PR once you open it.

In case you are not familiar with PRs, take a look here: https://help.github.com/articles/creating-a-pull-request/.

**Comment by mez** [comment]
closing as discussion will resume in the PR.
