### ISSUE TITLE
Can't run tests with ros_junit reporter

### ISSUE THREAD

**Issue by naveedhd** [AIS-Bonn/catch_ros#7]
the tests generated doesn't run with `ros_junit` as reported:

```
./catch_test -r ros_junit
No reporter registered with name: 'ros_junit'
```

Listing reporters give me the following:
```
./catch_test --list-reporters
Available reporters:
  compact:  Reports test results on a single line, suitable for IDEs
  console:  Reports test results as plain lines of text
  junit:    Reports test results in an XML format that looks like Ant's
              junitreport target
  xml:      Reports test results as an XML document
```

I have installed the package from apt.

Is there a step missing in my installation? ros_junit seems to be [registered as reporter](https://github.com/AIS-Bonn/catch_ros/blob/master/src/ros_junit_reporter.h#L349)..

**Comment by xqms** [comment]
Thanks for the report! Can you give me a bit more detail on how you compile your `catch_test` executable? Are you using the provided CMake macros?

**Comment by xqms** [comment]
On my setup everything works. The issue might be that you have your own definition of `main()` and don't use the provided runners (which are linked in by the provided CMake macros). In that case, the `ros_junit` reporter does not get registered (it needs to be included somewhere).

**Comment by naveedhd** [comment]
Thanks for the prompt response Max!

[Here](https://github.com/naveedhd/catch_ros_example) I have put up very minimal ros package with the example catch test.

As you mentioned, I think the problem might be this [line](https://github.com/naveedhd/catch_ros_example/blob/kinetic-devel/test/catch_test.cpp#L1) where I am using define macro from catch examples. Removing this causes the ros_junit to get registered and I can see in the list of reporters too.

**Comment by xqms** [comment]
Interesting. I had assumed that having a duplicate CATCH_CONFIG_MAIN would generate a linker error - but that is not the case, it just hides the definition of `main()` in the linked library. I'll put something into the README to help people in the future.
